<script setup lang="ts" name="MxMenus">
import type { TreeOption } from 'naive-ui'

const data = [
  {
    name: '10.11.8.71',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '10.11.8.71',
      group: '',
      hostAddress: '10.11.8.71',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'CnnsUni954.com',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'Cobalt_Neon',
      forwardIn: [],
      lineHeight: 1,
      letterSpacing: 1,
      fontFamily: 'JetBrains Mono',
      cursorStyle: 'bar',
      cursorBlink: true,
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8'
    },
    description: '',
    type: 'node',
    uuid: '99b1414d-0c66-4e48-9e66-62c844c7a5f9'
  },
  {
    name: '192.168.99.99',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '192.168.99.99',
      group: '',
      hostAddress: '10.11.8.99',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'Cnnslab178.net',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'Night_3024',
      forwardIn: [],
      fontFamily: 'JetBrains Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: 'cf2b6b3c-fca1-45a5-8ad3-3a7ce6fea744'
  },
  {
    name: '个人服务器',
    config: null,
    description: '',
    type: 'folder',
    uuid: '64aff190-9f0c-48fc-bf5c-f8503ad6f75f',
    subSessions: [
      {
        name: '群晖',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '群晖',
          group: '',
          hostAddress: 'nas.yuxi.fun',
          hostPort: 2615,
          authType: 'password',
          username: 'baizw',
          password: 'Muyu@891204',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: '',
        type: 'node',
        uuid: 'c0d64682-0582-4605-8aaa-59d598743bba'
      },
      {
        name: '175.178.84.218',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '175.178.84.218',
          group: '',
          hostAddress: '175.178.84.218',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Muyu@2023',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: 'telnet session',
        type: 'node',
        uuid: 'e81e3575-944d-4449-a588-f4164de4a131'
      },
      {
        name: '10.11.17.114',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '10.11.17.114',
          group: '',
          hostAddress: '10.11.17.114',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Cnns.net',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: 'telnet session',
        type: 'node',
        uuid: '77cc4fd4-fa03-4084-be46-1aa69ff38e20'
      },
      {
        name: '本地',
        config: {
          sessType: 'localshell',
          protocal: 'localshell',
          hostName: '本地',
          system: 'powershell',
          group: '',
          fontFamily: 'JetBrainsMono Nerd Font Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline',
          xtermTheme: 'default'
        },
        description: '',
        type: 'node',
        uuid: '5366682a-a3ac-4e85-87ad-bb720dd5381b'
      }
    ]
  },
  {
    name: '175.178.193.136-cnns',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'centos',
      hostName: '175.178.193.136-cnns',
      group: '',
      hostAddress: '175.178.193.136',
      hostPort: 22,
      authType: 'password',
      username: 'cnns',
      password: 'fp2QrKn$D1HY$g9(N',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'default',
      forwardIn: [],
      fontFamily: 'Cascadia Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1.2,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: '94402ec8-4e69-43d0-9520-3af1c8117681'
  },
  {
    name: '10.11.24.122',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '10.11.24.122',
      group: '',
      hostAddress: '10.11.24.122',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'Cnnsbzwtest623.net',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'Argonaut',
      forwardIn: [],
      fontFamily: 'JetBrains Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: '60008ad7-1161-4a12-b29a-97fceca82418'
  },
  {
    name: '192.168.1.161-01',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '192.168.1.161-01',
      group: '',
      hostAddress: '192.168.1.161',
      hostPort: 2201,
      authType: 'password',
      username: 'root',
      password: 'p37DqO1Av8c2',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'default',
      forwardIn: [],
      fontFamily: 'JetBrains Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: '58ac73db-5af4-4c56-b7bb-d8adaa29f83b'
  },
  {
    name: '10.11.8.70-杜诈内网',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '10.11.8.70-杜诈内网',
      group: '',
      hostAddress: '10.11.8.70',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'CnnsDataTrans.net',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'default',
      forwardIn: [],
      fontFamily: 'Cascadia Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: 'ccc231e1-4238-4de2-940d-5d0ac57da416'
  },
  {
    name: '10.11.8.99',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '10.11.8.99',
      group: '',
      hostAddress: '10.11.8.99',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'Cnnslab178.net',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'Afterglow',
      forwardIn: [],
      fontFamily: 'JetBrains Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: 'c461d239-ccf1-433f-af3b-654faee53bb4'
  },
  {
    name: '10.11.24.121',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '10.11.24.121',
      group: '',
      hostAddress: '10.11.24.121',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'Cnnsbzwdev623.net',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'Night_3024',
      forwardIn: [],
      fontFamily: 'JetBrains Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1.2,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: '9fb6fbee-e813-4f44-bc71-2459a774c5fa'
  },
  {
    name: '10.11.24.121',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'ssh',
      hostName: '10.11.24.121',
      group: '',
      hostAddress: '10.11.24.121',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: 'Cnnsbzwdev623.net',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'Night_3024',
      forwardIn: [],
      fontFamily: 'JetBrainsMono Nerd Font Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: '6fc95634-cff1-4244-8fea-8ece07ebd692'
  },
  {
    name: '175.178.193.136-root',
    config: {
      sessType: 'ssh',
      protocal: 'ssh',
      proxy: 'none',
      system: 'centos',
      hostName: '175.178.193.136-root',
      group: '',
      hostAddress: '175.178.193.136',
      hostPort: 22,
      authType: 'password',
      username: 'root',
      password: '7%v2B9*]w^FEa0zR(',
      cert: '',
      passphrase: '',
      proxyHost: '',
      proxyPort: 1080,
      forward: 'none',
      sftpDirt: '/',
      keepAliveInterval: 60,
      keepAliveCountMax: 3,
      readyTimeout: 20000,
      xtermTheme: 'default',
      forwardIn: [],
      fontFamily: 'JetBrains Mono',
      xterm: 'xterm',
      fontSize: '12',
      fontWeight: 'normal',
      charset: 'UTF-8',
      lineHeight: 1,
      letterSpacing: 1,
      cursorBlink: true,
      cursorStyle: 'underline'
    },
    description: '',
    type: 'node',
    uuid: '059b3122-b3c8-429d-8932-4f0c96efc7ab'
  },
  {
    name: 'xq',
    config: null,
    description: '',
    type: 'folder',
    uuid: '49e105ad-79b0-496f-87c2-3cbeb296fa59',
    subSessions: [
      {
        name: '猎鹰服务器',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '猎鹰服务器',
          group: '',
          hostAddress: '10.11.24.170',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Cnns.net',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'default',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1.2,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: '',
        type: 'node',
        uuid: '510555ac-2bb9-4fe4-8a6c-6d92906ac0f6'
      },
      {
        name: '长链',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '长链',
          group: '',
          hostAddress: '10.11.24.221',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Cnns132465xzy',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1.2,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: 'telnet session',
        type: 'node',
        uuid: 'fa888a52-6d11-4795-a36d-096a273c309d'
      },
      {
        name: '长弓项目',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '长弓项目',
          group: '',
          hostAddress: '10.11.24.222',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Cnns132465xzy',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1.2,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: 'telnet session',
        type: 'node',
        uuid: 'a9d40fb5-0129-4c42-9cfb-e77cb577571b'
      },
      {
        name: 'cgcl数据库',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: 'cgcl数据库',
          group: '',
          hostAddress: '10.11.24.225',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Cnns132465xzy',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1.2,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: '',
        type: 'node',
        uuid: '4ec29f34-57ff-4790-bc36-48751bd6e1ea'
      },
      {
        name: '10.11.24.185',
        config: {
          sessType: 'ssh',
          protocal: 'ssh',
          proxy: 'none',
          system: 'ssh',
          hostName: '10.11.24.185',
          group: '',
          hostAddress: '10.11.24.185',
          hostPort: 22,
          authType: 'password',
          username: 'root',
          password: 'Cnns132465xzy',
          cert: '',
          passphrase: '',
          proxyHost: '',
          proxyPort: 1080,
          forward: 'none',
          sftpDirt: '/',
          keepAliveInterval: 60,
          keepAliveCountMax: 3,
          readyTimeout: 20000,
          xtermTheme: 'default',
          forwardIn: [],
          fontFamily: 'JetBrains Mono',
          xterm: 'xterm',
          fontSize: '12',
          fontWeight: 'normal',
          charset: 'UTF-8',
          lineHeight: 1.2,
          letterSpacing: 1,
          cursorBlink: true,
          cursorStyle: 'underline'
        },
        description: 'telnet session',
        type: 'node',
        uuid: '09c22389-9742-4810-98c6-b23435154d77'
      }
    ]
  }
]
const pattern = ref('')
function nodeProps({ option }: { option: TreeOption }) {
  return {
    ondblclick() {
      window.$message?.success(`双击 ${option.name}`)
    },
    onContextmenu(e: MouseEvent): void {
      console.info('e', e)
    }
  }
}
</script>

<template>
  <n-flex vertical>
    <n-input v-model:value="pattern" placeholder="搜索" />
    <n-tree
      block-line
      block-node
      cascade
      expand-on-click
      :data="data"
      :pattern="pattern"
      :show-irrelevant-nodes="false"
      :node-props="nodeProps"
      key-field="uuid"
      label-field="name"
      children-field="subSessions"
      :selectable="false"
    />
  </n-flex>
</template>
